// Shown if GET /popular hasn't returned yet or during initial load,
// ensuring the Home page displays world-class curated destinations.
export const FALLBACK_DESTINATIONS = {
  family: [
    {
      id: "kerala",
      name: "Kerala",
      country: "India",
      tag: "Backwaters & Wildlife",
      rating: 4.92,
      reviews: 1420,
      priceFrom: "₹18,500",
      bestSeason: "Sep - Mar",
      duration: "5-6 Days",
      highlights: ["Alleppey Houseboat Stay", "Periyar Elephant Sanctuary", "Munnar Tea Estates"],
      image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "singapore",
      name: "Singapore",
      country: "Singapore",
      tag: "City & Theme Parks",
      rating: 4.88,
      reviews: 2150,
      priceFrom: "₹45,000",
      bestSeason: "Nov - Aug",
      duration: "4-5 Days",
      highlights: ["Universal Studios Sentosa", "Gardens by the Bay", "Night Safari Adventure"],
      image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "maldives",
      name: "Maldives",
      country: "Maldives",
      tag: "Overwater Family Villas",
      rating: 4.96,
      reviews: 980,
      priceFrom: "₹72,000",
      bestSeason: "Dec - Apr",
      duration: "5-7 Days",
      highlights: ["Coral Reef Snorkeling", "Dolphin Cruise", "Glass-Bottom Villas"],
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "switzerland",
      name: "Interlaken",
      country: "Switzerland",
      tag: "Alpine Lakes & Trains",
      rating: 4.94,
      reviews: 1670,
      priceFrom: "₹88,000",
      bestSeason: "May - Oct",
      duration: "6-8 Days",
      highlights: ["Jungfraujoch Top of Europe", "Lake Brienz Cruise", "Panoramic Cogwheel Trains"],
      image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "thailand",
      name: "Phuket",
      country: "Thailand",
      tag: "Island Cruises & Beach",
      rating: 4.79,
      reviews: 3200,
      priceFrom: "₹28,000",
      bestSeason: "Nov - Apr",
      duration: "5 Days",
      highlights: ["Phi Phi Island Speedboat", "Elephant Sanctuary", "Old Phuket Town Walk"],
      image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    },
  ],
  adventure: [
    {
      id: "leh-ladakh",
      name: "Leh Ladakh",
      country: "India",
      tag: "High Mountain Passes",
      rating: 4.95,
      reviews: 1840,
      priceFrom: "₹24,000",
      bestSeason: "Jun - Sep",
      duration: "7-8 Days",
      highlights: ["Khardung La Pass (17,582 ft)", "Pangong Tso Lake Camping", "Nubra Valley Sand Dunes"],
      image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "nepal",
      name: "Annapurna Base Camp",
      country: "Nepal",
      tag: "Himalayan Treks",
      rating: 4.91,
      reviews: 940,
      priceFrom: "₹32,000",
      bestSeason: "Mar - May, Oct - Nov",
      duration: "9-11 Days",
      highlights: ["Sunrise at Poon Hill", "Himalayan Sanctuary", "Hot Springs in Jhinu Danda"],
      image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "manali",
      name: "Manali & Solang",
      country: "India",
      tag: "Paragliding & Snow",
      rating: 4.78,
      reviews: 2890,
      priceFrom: "₹14,500",
      bestSeason: "Oct - Jun",
      duration: "4-5 Days",
      highlights: ["Atal Tunnel Exploration", "Solang Valley Skiing", "Old Manali Cafes"],
      image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "rishikesh",
      name: "Rishikesh",
      country: "India",
      tag: "River Rafting & Cliff Jumps",
      rating: 4.87,
      reviews: 3100,
      priceFrom: "₹9,500",
      bestSeason: "Sep - Nov, Mar - May",
      duration: "3-4 Days",
      highlights: ["Grade IV Ganga Rafting", "Bungee Jumping from 83m", "Evening Ganga Aarti"],
      image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "queenstown",
      name: "Queenstown",
      country: "New Zealand",
      tag: "World Adventure Capital",
      rating: 4.98,
      reviews: 1350,
      priceFrom: "₹95,000",
      bestSeason: "Dec - Mar (Summer), Jul - Aug (Ski)",
      duration: "6-8 Days",
      highlights: ["Nevis Bungy 134m", "Milford Sound Scenic Flight", "Shotover Jet Boating"],
      image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800&q=80",
    },
  ],
  friends: [
    {
      id: "goa",
      name: "North Goa",
      country: "India",
      tag: "Sunsets & Nightlife",
      rating: 4.84,
      reviews: 4200,
      priceFrom: "₹12,000",
      bestSeason: "Nov - Feb",
      duration: "4-5 Days",
      highlights: ["Vagator Sunset Lounges", "Scuba at Grand Island", "Anjuna Flea Market"],
      image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "dubai",
      name: "Dubai",
      country: "UAE",
      tag: "Skyline & Desert Safari",
      rating: 4.91,
      reviews: 3100,
      priceFrom: "₹42,000",
      bestSeason: "Nov - Mar",
      duration: "5-6 Days",
      highlights: ["Dune Bashing & BBQ Camp", "Burj Khalifa 148th Floor", "Yacht Tour at Dubai Marina"],
      image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "bangkok",
      name: "Bangkok",
      country: "Thailand",
      tag: "Street Food & Rooftops",
      rating: 4.82,
      reviews: 2950,
      priceFrom: "₹26,000",
      bestSeason: "Nov - Feb",
      duration: "4-5 Days",
      highlights: ["Chatuchak Weekend Market", "Chao Phraya River Cruise", "Rooftop Skybars"],
      image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "barcelona",
      name: "Barcelona",
      country: "Spain",
      tag: "Tapas & Architecture",
      rating: 4.93,
      reviews: 2400,
      priceFrom: "₹68,000",
      bestSeason: "May - Oct",
      duration: "6-7 Days",
      highlights: ["Sagrada Família Guided Access", "Barceloneta Beach Parties", "Gothic Quarter Tapas Crawl"],
      image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80",
    },
  ],
  solo: [
    {
      id: "bali",
      name: "Ubud & Canggu",
      country: "Indonesia",
      tag: "Cafes & Rice Terraces",
      rating: 4.93,
      reviews: 1980,
      priceFrom: "₹34,000",
      bestSeason: "Apr - Oct",
      duration: "7-10 Days",
      highlights: ["Tegallalang Sunrise Swing", "Yoga Barn Wellness Retreat", "Echo Beach Surf Lessons"],
      image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "kyoto",
      name: "Kyoto",
      country: "Japan",
      tag: "Zen Gardens & Temples",
      rating: 4.97,
      reviews: 2310,
      priceFrom: "₹65,000",
      bestSeason: "Mar - May (Cherry Blossom), Oct - Nov (Autumn)",
      duration: "6-8 Days",
      highlights: ["Fushimi Inari Early Morning", "Arashiyama Bamboo Grove", "Traditional Tea Ceremony in Gion"],
      image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "santorini",
      name: "Santorini",
      country: "Greece",
      tag: "Cliffside Views & Blue Domes",
      rating: 4.94,
      reviews: 1720,
      priceFrom: "₹76,000",
      bestSeason: "May - Oct",
      duration: "5-6 Days",
      highlights: ["Oia Sunset Walk", "Red Beach Hike", "Volcano Boat Tour"],
      image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "lisbon",
      name: "Lisbon",
      country: "Portugal",
      tag: "Historic Trams & Viewpoints",
      rating: 4.89,
      reviews: 1540,
      priceFrom: "₹48,000",
      bestSeason: "Mar - May, Sep - Oct",
      duration: "5 Days",
      highlights: ["Tram 28 Historic Ride", "Belém Pastéis Tasting", "Miradouro Sunsets"],
      image: "https://images.unsplash.com/photo-1513326738677-b964603b136d?auto=format&fit=crop&w=800&q=80",
    },
  ],
  couple: [
    {
      id: "santorini",
      name: "Santorini Caldera",
      country: "Greece",
      tag: "Sunset Caldera Stays",
      rating: 4.98,
      reviews: 2840,
      priceFrom: "₹78,000",
      bestSeason: "May - Oct",
      duration: "5-7 Days",
      highlights: ["Private Infinity Pool Suite", "Caldera Sunset Catamaran", "Candlelit Cliffside Dining"],
      image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "maldives",
      name: "Baa Atoll",
      country: "Maldives",
      tag: "Private Island Retreat",
      rating: 4.99,
      reviews: 1890,
      priceFrom: "₹85,000",
      bestSeason: "Dec - Apr",
      duration: "5-6 Days",
      highlights: ["Overwater Sunrise Villa", "Private Sandbank Lunch", "Manta Ray Snorkeling"],
      image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "paris",
      name: "Paris",
      country: "France",
      tag: "Eiffel Nights & Seine Walks",
      rating: 4.92,
      reviews: 3120,
      priceFrom: "₹64,000",
      bestSeason: "Apr - Jun, Sep - Nov",
      duration: "5-7 Days",
      highlights: ["Evening Seine River Cruise", "Montmartre Art Stroll", "Michelin Dining in Le Marais"],
      image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80",
    },
    {
      id: "udaipur",
      name: "Udaipur",
      country: "India",
      tag: "Lake Palaces & Royalty",
      rating: 4.94,
      reviews: 2150,
      priceFrom: "₹26,000",
      bestSeason: "Oct - Mar",
      duration: "4-5 Days",
      highlights: ["Lake Pichola Boat Ride", "Jag Mandir Palace Visit", "Rooftop Haveli Dining"],
      image: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
    },
  ],
};

